FROM mysql:latest

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

ENV MYSQL_DATABASE=shelter \
    MYSQL_ROOT_PASSWORD=test

# All files *.sql found in dest location will be executed, more info can be
# found in the official container image docs on docker hub
ADD 00-schema.sql /docker-entrypoint-initdb.d
ADD 01-fill_with_data.sql /docker-entrypoint-initdb.d

EXPOSE 3306
